//
//  K.swift
//  DayCraft
//
//  Created by Nihal Ismail on 11/21/23.
//

import Foundation

struct K{
    static let icons = [
        "person.fill",
        "alarm.fill",
        "sun.max.fill",
        "shower.fill",
        "bathtub.fill",
        "figure.mind.and.body",
        "figure.walk",
        "figure.run",
        "house.fill",
        "fork.knife.circle.fill",
        "cup.and.saucer.fill",
        "waterbottle.fill",
        "briefcase.fill",
        "macbook",
        "phone.fill",
        "car.side.fill",
        "bus",
        "airplane",
        "tram.fill",
        "ferry.fill",
        "bicycle",
        "fuelpump.fill",
        "ev.charger.fill",
        "sunset.fill",
        "book.fill",
        "bolt.fill",
        "cart.fill",
        "cat.fill",
        "dog.fill",
        "tray.fill",
        "wineglass.fill",
        "tv.fill",
        "moon.fill",
        "bed.double.fill",
        "pill.fill",
        "figure.walk.arrival",
        "figure.walk.departure",
        "figure.strengthtraining.traditional",
        "figure.yoga",
        "figure.mixed.cardio",
        "figure.american.football",
        "figure.archery",
        "figure.australian.football",
        "figure.badminton",
        "figure.baseball",
        "figure.basketball",
        "figure.bowling",
        "figure.cricket",
        "figure.soccer",
        "figure.pool.swim",
        "figure.boxing",
        "figure.core.training",
        "figure.elliptical",
        "figure.fishing",
        "figure.fencing",
        "figure.strengthtraining.functional",
        "figure.hiking",
        "figure.hockey",
        "figure.jumprope",
        "figure.tennis",
        "figure.surfing",
        "figure.skating",
        "gamecontroller.fill",
        "football.fill",
        "basketball.fill",
        "soccerball",
        "baseball.fill",
        "tennis.racket",
        "cricket.ball.fill",
        "volleyball.fill"
    ]
}
